/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-background": "var(--color-on-background)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "on-primary": "var(--color-on-primary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface": "var(--color-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "error-container": "var(--color-error-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "primary": "var(--color-primary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "error": "var(--color-error)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "background": "var(--color-background)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "outline": "var(--color-outline)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-error": "var(--color-on-error)",
        "outline-variant": "var(--color-outline-variant)",
        "primary-container": "var(--color-primary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.625rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "sans": ["Tajawal", "Inter", "sans-serif"],
        "display": ["Inter", "Tajawal", "sans-serif"],
        "mono": ["JetBrains Mono", "Fira Code", "monospace"]
      },
      fontSize: {
        "display-lg":  ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm":     ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md":    ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm":    ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        "emerald-sm":  "0 0 12px rgba(16, 185, 129, 0.2)",
        "emerald-md":  "0 0 24px rgba(16, 185, 129, 0.3)",
        "emerald-lg":  "0 0 40px rgba(16, 185, 129, 0.4)",
        "indigo-sm":   "0 0 12px rgba(129, 140, 248, 0.2)",
        "card":        "0 4px 30px rgba(0, 0, 0, 0.4)",
        "card-hover":  "0 12px 50px rgba(0, 0, 0, 0.5), 0 0 20px rgba(16,185,129,0.06)",
      },
      backdropBlur: {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "20px",
        "2xl": "30px"
      },
      animation: {
        "pulse-soft":  "pulse-soft 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in":     "fade-in 0.5s ease-out forwards",
        "slide-up":    "slide-up 0.6s ease-out forwards",
        "glow-pulse":  "glow-pulse 2s ease-in-out infinite",
        "float":       "float 3s ease-in-out infinite",
      }
    },
  },
  plugins: [],
}
